# This is a basic workflow to help you get started with Actions

name: A Basic Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  name: Ajmal
  Degree: CSE

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment:
      name: Test Environment
      url:  https://github.com

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
         echo Hello, world!,
         echo "Globally printing my name $name"
         echo "Globally printing my degree ${{env.Degree}}"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
    
  build-db:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Run a sample script
        run: echo Hello Windows

  build-api:
    runs-on: windows-latest
    steps:
      - name: Run a sample script
        run: |
         echo Building API,
         echo "printing name inside step locally ${{env.name}}"
         echo "printing secret ===> ${{secrets.SECRET_KEY_CUSTOM}}"
    env:
      name: ajmal-test

  package:
   needs: [build,build-db]
   runs-on: macos-latest
   steps:
    - name: Run a sample script
      run: echo Hello Mac
